name: mcp_dart
description: Dart Implementation of Model Context Protocol (MCP) SDK.
version: 0.5.1
repository: https://github.com/leehack/mcp_dart

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.1
  uuid: ^4.4.0
  web: ^0.5.1
  eventflux: ^2.2.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
