name: fetch_server
description: A stdio-based MCP server for fetching website content.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mcp_dart:
    path: ../../
  http: ^1.0.0
  args: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.25.15
