name: Run Tests on PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Running tests with coverage
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Post coverage comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Code Coverage Report
          message: |
            ```plaintext
            $(curl -s https://codecov.io/github/${{ github.repository }}/commit/${{ github.sha }}/coverage)
            ```
